### ISSUE TITLE
`Gempyre::set_debug(true)` does not enable web inspector in python GUI

### ISSUE THREAD

**Issue by Ma5t3rful** [mmertama/Gempyre#9]
@mmertama
in 1.0.1
step to reproduce:
1. Open a gempyre project
2. `Gempyre::set_debug(true)`
3. Build the example with python UI.
4. python UI does not pull up the web inspector. 

It seems that `Debug=true` won't pass into pywebview.

**Comment by mmertama** [comment]
Are you using USE_PYTHON_UI option when building? Can you elaborate Debug=true, do you mean that web inspector window should be visible then - or it does not open on right click?

**Comment by Ma5t3rful** [comment]
> Are you using USE_PYTHON_UI option when building? 

Yes

> Can you elaborate Debug=true

pywebview uses `webview.start(Debug=True)` to enable web inspector. in previous versions gempyre used to pass this variable to `webview.start()` when you set `Gempyre::set_debug()` to true.

> do you mean that web inspector window should be visible then - or it does not open on right click?

I mean that it is completely disabled when you enable `Gempyre::set_debug()`. when you enable debugging, python webview should have web inspector plus a context menu just like before.

**Comment by mmertama** [comment]
Sorry I forgot what was my intention: Instead of doing such "UI client" specific implementation, the API was changed to provide "browser parameters"
`    /// Create UI using given ui app and command line
        Ui(const Filemap& filemap, const std::string& indexHtml, const std::string& browser,  const std::string& browser_params, unsigned short port = UseDefaultPort, const std::string& root = UseDefaultRoot);
`
Unfortunately there was a bug and it did not work well with non-string parameters. I will fix that within next version. (branch random_fixes_2)

For example: `    Gempyre::Ui ui({{"/main.html", Mainhtml}}, "main.html", "", "debug=True");
`

**Comment by Ma5t3rful** [comment]
Great, BTW, for next versions, would you please use github relaeses? They are a lot easier to track when you want to switch between versions.
